package pl.streamsoft.verto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-01T08:23:18.735+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://verto.streamsoft.pl", name = "GoodWebService")
@XmlSeeAlso({org.eclipse.webtools.catalogue.ObjectFactory.class, ObjectFactory.class})
public interface GoodWebService {

    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://verto.streamsoft.pl", className = "pl.streamsoft.verto.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://verto.streamsoft.pl", className = "pl.streamsoft.verto.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public pl.streamsoft.verto.GoodWO get(
        @WebParam(name = "index", targetNamespace = "")
        java.lang.String index
    ) throws WebServiceException_Exception;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "bookResponse", targetNamespace = "http://www.eclipse.org/webtools/Catalogue", partName = "parameters")
    public org.eclipse.webtools.catalogue.BookType getBook(
        @WebParam(partName = "parameters", name = "get", targetNamespace = "http://www.eclipse.org/webtools/Catalogue")
        org.eclipse.webtools.catalogue.Get parameters
    );
}
