
package pl.streamsoft.verto;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-01T08:23:18.717+01:00
 * Generated source version: 3.3.0
 */

@WebFault(name = "WebServiceException", targetNamespace = "http://verto.streamsoft.pl")
public class WebServiceException_Exception extends Exception {

    private pl.streamsoft.verto.WebServiceException webServiceException;

    public WebServiceException_Exception() {
        super();
    }

    public WebServiceException_Exception(String message) {
        super(message);
    }

    public WebServiceException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WebServiceException_Exception(String message, pl.streamsoft.verto.WebServiceException webServiceException) {
        super(message);
        this.webServiceException = webServiceException;
    }

    public WebServiceException_Exception(String message, pl.streamsoft.verto.WebServiceException webServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.webServiceException = webServiceException;
    }

    public pl.streamsoft.verto.WebServiceException getFaultInfo() {
        return this.webServiceException;
    }
}
